spring:
  application:
    name: apiInSpringBoot
  datasource:
    url: jdbc:postgresql://localhost:6578/esy_bosch
    username: postgres
    password: root
  jpa:
    properties:
      show-sql: true
      format_sql: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        provider:
          azure-ad:
            authorization-uri: ${AUTHORIZATION_URI}
            token-uri: ${TOKEN_URI}
            jwk-set-uri: ${JWK_SET_URI}
        registration:
          azure-client:
            provider: azure-ad
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid








upload:
  dir: ${user.dir}/eventsUploads

server:
  error:
    include-stacktrace: never
  port: 6967

